### ISSUE TITLE
incompatible with flask 2 and async

### ISSUE THREAD

**Issue by abulka** [flask-debugtoolbar/flask-debugtoolbar#158]
It seems that flask-debugtoolbar is incompatible with flask 2 async endpoints.

Repro:

Run this flask project (app.py) and hit `/data` to trigger an async call - which works.

Then uncomment the line enabling the `DebugToolbarExtension` and we get an exception.

```python
import asyncio
from flask import Flask
from flask import render_template
from icecream import ic
from flask_debugtoolbar import DebugToolbarExtension

app = Flask(__name__)

app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0
app.config['JSON_SORT_KEYS'] = False
app.secret_key = 'super secret key'

# flask debug toolbar - https://flask-debugtoolbar.readthedocs.io/en/latest/index.html#configuration
app.debug = True
app.config['DEBUG_TB_INTERCEPT_REDIRECTS'] = False
app.config['DEBUG_TB_TEMPLATE_EDITOR_ENABLED'] = True
# toolbar = DebugToolbarExtension(app)  # <<<< UNCOMMENT THIS AND WATCH IT CRASH

@app.route('/')
def root():
    return "hi"


async def async_get_data():
    ic('in async function')
    await asyncio.sleep(2)
    ic('out of async function')
    return 'Done!'


@app.route("/data")
async def get_data():
    data = await async_get_data()
    return data
```

**Comment by renegadevi** [comment]
Same issue when using async. I am getting this error message.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1727, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a coroutine.
 ```

**Comment by jeffwidman** [comment]
Happy to merge a PR if you or anyone else wants to dig into it. 

On the surface, it looks relatively straightforward--port the updated version from `Flask` itself into here, along with the update to call `process_view`, but I'm sure there's a wrinkle or two to keep things interesting.

My current work is unrelated to Flask, so won't have time to look into it myself anytime soon.

**Comment by caarmen** [comment]
I've quickly tried the following hack/changes. Seems to work:

:one: override `DebugToolbarExtension` to handle coroutines:
```python
from asyncio import iscoroutinefunction
from asgiref.sync import async_to_sync
from flask_debugtoolbar import DebugToolbarExtension

class MyDebugToolbarExtension(DebugToolbarExtension):
    def process_view(self, app, view_func, view_kwargs):
        processed_view = super().process_view(app, view_func, view_kwargs)
        if iscoroutinefunction(processed_view):
            processed_view = async_to_sync(processed_view)
        return processed_view
```

:two: Enable sql query recording of an async engine:
```python
from flask_sqlalchemy import record_queries
from sqlalchemy.ext.asyncio import create_async_engine


engine = create_async_engine(db_url)
record_queries._listen(engine.sync_engine)
```

Note that this is calling a "private" function, `_listen` in the `record_queries` module.
